### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by johanoskarsson** [railsware/capistrano-strategy-copy-partial#1]
I've been looking for a gem that solves this particular problem and I just found yours. It looks great, will give it a spin. 

Unfortunately for me to be able to use it I suspect I need to know if there are any licensing restrictions. My project is under Apache 2 so hopefully this code could be used together with that.

Thanks!

**Comment by cris** [comment]
Hi @johanoskarsson .

It's released under MIT-licence. I've updated README. Thanks for your notice.
